N_CLIENTS: 10
MODEL_TYPE: 'dnn' # CNN or DNN
N_ROUNDS: 10
DATASET: 'fashion_mnist' ## QUANDO MUDAR DE DATASET LEMBRA DE MUDAR O DIRICHLET
SEL_INVITATION: 'poc' 
FIT_METHOD: 'avg'
AGG_METHOD: 'yogi'
AWARNESSE: True